spring:
  profiles:
    group:
      "local": "local-profile,common"
      "prod": "prod-profile,common"
    default: "prod"

---
spring:
  config:
    activate:
      on-profile: "common"
  jpa:
    database: mysql
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 550MB
      max-request-size: 550MB
  lifecycle:
    timeout-per-shutdown-phase: 35s

server:
  servlet:
    session:
      cookie:
        name: AI4XSESSION
  port: 9090

---
spring:
  config:
    activate:
      on-profile: "local-profile"

logging:
  config: classpath:logback-local.xml

ai4x:
  py4spring:
    convert: true
    pythonDirectory: C:\Temp\python
  docker:
    host: tcp://localhost:2375
    max: 100
    timeout: 30
#    tls: false
#    tlsCert:
#    registry:
#      username: siyang12@gmail.com
#      password: kailos0601
#      email: siyang12@gmail.com
#      url: url

---
spring:
  config:
    activate:
      on-profile: "prod-profile"

logging:
  config: classpath:logback-prod.xml
